# Generated by Django 4.0.4 on 2022-06-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appinmob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='poseecartel',
            field=models.CharField(max_length=2),
        ),
    ]
